[package]
name = "gpui-vue"
version = "0.1.0"
edition = "2024"
description = "A Vue-inspired, compile-time view DSL for GPUI"
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[workspace]
members = ["gpui-vue-macros"]
resolver = "3"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
missing_docs_in_private_items = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
bare_urls = "deny"

[features]
default = []
desktop = ["gpui/font-kit", "gpui/wayland", "gpui/x11"]

[dependencies]
gpui = { version = "=0.2.2", default-features = false }
gpui-vue-macros = { path = "gpui-vue-macros", version = "0.1.0" }

[[example]]
name = "counter"
required-features = ["desktop"]

[dev-dependencies]
trybuild = "1.0.120"
