//! Tailwind CSS 4.3.2 default colors lowered to packed sRGB.
//!
//! The source values are the 286 `oklch(...)` declarations in
//! `package/theme.css` from the official `tailwindcss-4.3.2.tgz` npm artifact
//! (SHA-1 `408ee67d767a0fef7b174674bb9c5ce136a5ace1`). The table was generated by
//! converting OKLCH to OKLab, applying the CSS Color 4 OKLab-to-linear-sRGB
//! matrix and sRGB transfer function, clamping every encoded channel to
//! `[0, 1]`, and rounding to the nearest 8-bit channel.
//!
//! GPUI 0.2.2's packed `rgb(u32)` path cannot preserve an OKLCH color or a
//! wide-gamut component. Direct channel clamping is deterministic and cheap,
//! but a browser or another color-managed host may use a perceptual gamut
//! mapping algorithm or a wider output gamut and therefore render an
//! out-of-sRGB Tailwind color differently. Keeping the generated table here
//! makes native GPUI output stable and leaves no color conversion in either
//! macro-expanded code or the application render path.

/// Number of named shade steps in each Tailwind palette.
const SHADE_COUNT: usize = 11;

/// Number of default Tailwind 4.3.2 palette families.
const PALETTE_COUNT: usize = 26;

/// Packed `0xRRGGBB` colors, ordered by family and then `50` through `950`.
///
/// Family order is the same as [`palette_index`]. Shade order is the same as
/// [`shade_index`]. Comments retain the official family names so updates can
/// be audited against the package source without changing the lookup API.
const PALETTES: [[u32; SHADE_COUNT]; PALETTE_COUNT] = [
    // red
    [
        0x00fe_f2f2,
        0x00ff_e2e2,
        0x00ff_c9c9,
        0x00ff_a2a2,
        0x00ff_6467,
        0x00fb_2c36,
        0x00e7_000b,
        0x00c1_0007,
        0x009f_0712,
        0x0082_181a,
        0x0046_0809,
    ],
    // orange
    [
        0x00ff_f7ed,
        0x00ff_edd4,
        0x00ff_d6a7,
        0x00ff_b86a,
        0x00ff_8904,
        0x00ff_6900,
        0x00f5_4900,
        0x00ca_3500,
        0x009f_2d00,
        0x007e_2a0c,
        0x0044_1306,
    ],
    // amber
    [
        0x00ff_fbeb,
        0x00fe_f3c6,
        0x00fe_e685,
        0x00ff_d230,
        0x00ff_b900,
        0x00fe_9a00,
        0x00e1_7100,
        0x00bb_4d00,
        0x0097_3c00,
        0x007b_3306,
        0x0046_1901,
    ],
    // yellow
    [
        0x00fe_fce8,
        0x00fe_f9c2,
        0x00ff_f085,
        0x00ff_df20,
        0x00fd_c700,
        0x00f0_b100,
        0x00d0_8700,
        0x00a6_5f00,
        0x0089_4b00,
        0x0073_3e0a,
        0x0043_2004,
    ],
    // lime
    [
        0x00f7_fee7,
        0x00ec_fcca,
        0x00d8_f999,
        0x00bb_f451,
        0x009a_e600,
        0x007c_cf00,
        0x005e_a500,
        0x0049_7d00,
        0x003c_6300,
        0x0035_530e,
        0x0019_2e03,
    ],
    // green
    [
        0x00f0_fdf4,
        0x00dc_fce7,
        0x00b9_f8cf,
        0x007b_f1a8,
        0x0005_df72,
        0x0000_c950,
        0x0000_a63e,
        0x0000_8236,
        0x0001_6630,
        0x000d_542b,
        0x0003_2e15,
    ],
    // emerald
    [
        0x00ec_fdf5,
        0x00d0_fae5,
        0x00a4_f4cf,
        0x005e_e9b5,
        0x0000_d492,
        0x0000_bc7d,
        0x0000_9966,
        0x0000_7a55,
        0x0000_6045,
        0x0000_4f3b,
        0x0000_2c22,
    ],
    // teal
    [
        0x00f0_fdfa,
        0x00cb_fbf1,
        0x0096_f7e4,
        0x0046_ecd5,
        0x0000_d5be,
        0x0000_bba7,
        0x0000_9689,
        0x0000_786f,
        0x0000_5f5a,
        0x000b_4f4a,
        0x0002_2f2e,
    ],
    // cyan
    [
        0x00ec_feff,
        0x00ce_fafe,
        0x00a2_f4fd,
        0x0053_eafd,
        0x0000_d3f2,
        0x0000_b8db,
        0x0000_92b8,
        0x0000_7595,
        0x0000_5f78,
        0x0010_4e64,
        0x0005_3345,
    ],
    // sky
    [
        0x00f0_f9ff,
        0x00df_f2fe,
        0x00b8_e6fe,
        0x0074_d4ff,
        0x0000_bcff,
        0x0000_a6f4,
        0x0000_84d1,
        0x0000_69a8,
        0x0000_598a,
        0x0002_4a70,
        0x0005_2f4a,
    ],
    // blue
    [
        0x00ef_f6ff,
        0x00db_eafe,
        0x00be_dbff,
        0x008e_c5ff,
        0x0051_a2ff,
        0x002b_7fff,
        0x0015_5dfc,
        0x0014_47e6,
        0x0019_3cb8,
        0x001c_398e,
        0x0016_2456,
    ],
    // indigo
    [
        0x00ee_f2ff,
        0x00e0_e7ff,
        0x00c6_d2ff,
        0x00a3_b3ff,
        0x007c_86ff,
        0x0061_5fff,
        0x004f_39f6,
        0x0043_2dd7,
        0x0037_2aac,
        0x0031_2c85,
        0x001e_1a4d,
    ],
    // violet
    [
        0x00f5_f3ff,
        0x00ed_e9fe,
        0x00dd_d6ff,
        0x00c4_b4ff,
        0x00a6_84ff,
        0x008e_51ff,
        0x007f_22fe,
        0x0070_08e7,
        0x005d_0ec0,
        0x004d_179a,
        0x002f_0d68,
    ],
    // purple
    [
        0x00fa_f5ff,
        0x00f3_e8ff,
        0x00e9_d4ff,
        0x00da_b2ff,
        0x00c2_7aff,
        0x00ad_46ff,
        0x0098_10fa,
        0x0082_00db,
        0x006e_11b0,
        0x0059_168b,
        0x003c_0366,
    ],
    // fuchsia
    [
        0x00fd_f4ff,
        0x00fa_e8ff,
        0x00f6_cfff,
        0x00f4_a8ff,
        0x00ed_6aff,
        0x00e1_2afb,
        0x00c8_00de,
        0x00a8_00b7,
        0x008a_0194,
        0x0072_1378,
        0x004b_004f,
    ],
    // pink
    [
        0x00fd_f2f8,
        0x00fc_e7f3,
        0x00fc_cee8,
        0x00fd_a5d5,
        0x00fb_64b6,
        0x00f6_339a,
        0x00e6_0076,
        0x00c6_005c,
        0x00a3_004c,
        0x0086_1043,
        0x0051_0424,
    ],
    // rose
    [
        0x00ff_f1f2,
        0x00ff_e4e6,
        0x00ff_ccd3,
        0x00ff_a1ad,
        0x00ff_637e,
        0x00ff_2056,
        0x00ec_003f,
        0x00c7_0036,
        0x00a5_0036,
        0x008b_0836,
        0x004d_0218,
    ],
    // slate
    [
        0x00f8_fafc,
        0x00f1_f5f9,
        0x00e2_e8f0,
        0x00ca_d5e2,
        0x0090_a1b9,
        0x0062_748e,
        0x0045_556c,
        0x0031_4158,
        0x001d_293d,
        0x000f_172b,
        0x0002_0618,
    ],
    // gray
    [
        0x00f9_fafb,
        0x00f3_f4f6,
        0x00e5_e7eb,
        0x00d1_d5dc,
        0x0099_a1af,
        0x006a_7282,
        0x004a_5565,
        0x0036_4153,
        0x001e_2939,
        0x0010_1828,
        0x0003_0712,
    ],
    // zinc
    [
        0x00fa_fafa,
        0x00f4_f4f5,
        0x00e4_e4e7,
        0x00d4_d4d8,
        0x009f_9fa9,
        0x0071_717b,
        0x0052_525c,
        0x003f_3f46,
        0x0027_272a,
        0x0018_181b,
        0x0009_090b,
    ],
    // neutral
    [
        0x00fa_fafa,
        0x00f5_f5f5,
        0x00e5_e5e5,
        0x00d4_d4d4,
        0x00a1_a1a1,
        0x0073_7373,
        0x0052_5252,
        0x0040_4040,
        0x0026_2626,
        0x0017_1717,
        0x000a_0a0a,
    ],
    // stone
    [
        0x00fa_faf9,
        0x00f5_f5f4,
        0x00e7_e5e4,
        0x00d6_d3d1,
        0x00a6_a09b,
        0x0079_716b,
        0x0057_534d,
        0x0044_403b,
        0x0029_2524,
        0x001c_1917,
        0x000c_0a09,
    ],
    // mauve
    [
        0x00fa_fafa,
        0x00f3_f1f3,
        0x00e7_e4e7,
        0x00d7_d0d7,
        0x00a8_9ea9,
        0x0079_697b,
        0x0059_4c5b,
        0x0046_3947,
        0x002a_212c,
        0x001d_161e,
        0x000c_090c,
    ],
    // olive
    [
        0x00fb_fbf9,
        0x00f4_f4f0,
        0x00e8_e8e3,
        0x00d8_d8d0,
        0x00ab_ab9c,
        0x007c_7c67,
        0x005b_5b4b,
        0x0047_4739,
        0x002b_2b22,
        0x001d_1d16,
        0x000c_0c09,
    ],
    // mist
    [
        0x00f9_fbfb,
        0x00f1_f3f3,
        0x00e3_e7e8,
        0x00d0_d6d8,
        0x009c_a8ab,
        0x0067_787c,
        0x004b_585b,
        0x0039_4447,
        0x0022_292b,
        0x0016_1b1d,
        0x0009_0b0c,
    ],
    // taupe
    [
        0x00fb_faf9,
        0x00f3_f1f1,
        0x00e8_e4e3,
        0x00d8_d2d0,
        0x00ab_a09c,
        0x007c_6d67,
        0x005b_4f4b,
        0x0047_3c39,
        0x002b_2422,
        0x001d_1816,
        0x000c_0a09,
    ],
];

/// Resolves one Tailwind color name to a packed `0xRRGGBB` sRGB value.
///
/// The accepted names are `black`, `white`, and every combination of the 26
/// Tailwind 4.3.2 default families with shades `50`, `100` through `900`, and
/// `950`. Parsing and lookup run only while expanding the view macro.
pub(super) fn rgb(name: &str) -> Option<u32> {
    match name {
        "black" => return Some(0x0000_0000),
        "white" => return Some(0x00ff_ffff),
        _ => {}
    }

    let (family, shade) = name.rsplit_once('-')?;
    Some(PALETTES[palette_index(family)?][shade_index(shade)?])
}

/// Maps an official Tailwind family name to its row in [`PALETTES`].
fn palette_index(family: &str) -> Option<usize> {
    Some(match family {
        "red" => 0,
        "orange" => 1,
        "amber" => 2,
        "yellow" => 3,
        "lime" => 4,
        "green" => 5,
        "emerald" => 6,
        "teal" => 7,
        "cyan" => 8,
        "sky" => 9,
        "blue" => 10,
        "indigo" => 11,
        "violet" => 12,
        "purple" => 13,
        "fuchsia" => 14,
        "pink" => 15,
        "rose" => 16,
        "slate" => 17,
        "gray" => 18,
        "zinc" => 19,
        "neutral" => 20,
        "stone" => 21,
        "mauve" => 22,
        "olive" => 23,
        "mist" => 24,
        "taupe" => 25,
        _ => return None,
    })
}

/// Maps a Tailwind shade suffix to its column in [`PALETTES`].
fn shade_index(shade: &str) -> Option<usize> {
    Some(match shade {
        "50" => 0,
        "100" => 1,
        "200" => 2,
        "300" => 3,
        "400" => 4,
        "500" => 5,
        "600" => 6,
        "700" => 7,
        "800" => 8,
        "900" => 9,
        "950" => 10,
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    //! Coverage for the generated Tailwind 4.3.2 color table.

    use super::*;

    /// Ensures every family exposes all eleven official shade steps.
    #[test]
    fn exposes_every_shade_of_every_palette() {
        for family in [
            "red", "orange", "amber", "yellow", "lime", "green", "emerald", "teal", "cyan", "sky",
            "blue", "indigo", "violet", "purple", "fuchsia", "pink", "rose", "slate", "gray",
            "zinc", "neutral", "stone", "mauve", "olive", "mist", "taupe",
        ] {
            for shade in [
                "50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950",
            ] {
                let name = format!("{family}-{shade}");
                assert!(rgb(&name).is_some(), "missing {name}");
            }
        }
    }

    /// Pins one generated midpoint from every official palette family.
    #[test]
    fn matches_representative_generated_values() {
        for (name, expected) in [
            ("red-500", 0x00fb_2c36),
            ("orange-500", 0x00ff_6900),
            ("amber-500", 0x00fe_9a00),
            ("yellow-500", 0x00f0_b100),
            ("lime-500", 0x007c_cf00),
            ("green-500", 0x0000_c950),
            ("emerald-500", 0x0000_bc7d),
            ("teal-500", 0x0000_bba7),
            ("cyan-500", 0x0000_b8db),
            ("sky-500", 0x0000_a6f4),
            ("blue-500", 0x002b_7fff),
            ("indigo-500", 0x0061_5fff),
            ("violet-500", 0x008e_51ff),
            ("purple-500", 0x00ad_46ff),
            ("fuchsia-500", 0x00e1_2afb),
            ("pink-500", 0x00f6_339a),
            ("rose-500", 0x00ff_2056),
            ("slate-500", 0x0062_748e),
            ("gray-500", 0x006a_7282),
            ("zinc-500", 0x0071_717b),
            ("neutral-500", 0x0073_7373),
            ("stone-500", 0x0079_716b),
            ("mauve-500", 0x0079_697b),
            ("olive-500", 0x007c_7c67),
            ("mist-500", 0x0067_787c),
            ("taupe-500", 0x007c_6d67),
        ] {
            assert_eq!(rgb(name), Some(expected), "mismatch for {name}");
        }
    }

    /// Handles singleton colors and rejects non-default names and shades.
    #[test]
    fn handles_singletons_and_invalid_names() {
        assert_eq!(rgb("black"), Some(0x0000_0000));
        assert_eq!(rgb("white"), Some(0x00ff_ffff));
        assert_eq!(rgb("red-0"), None);
        assert_eq!(rgb("brand-500"), None);
        assert_eq!(rgb("transparent"), None);
    }
}
